Attempt to resolve issues with roles differences between k8 and oscp
openshift/open-service-broker-sdk pull request #24
Opened 2017-05-18 20:54 UTC by maleck13

@bparees PTAL when you have a min. Should resolve https://github.com/openshift/open-service-broker-sdk/issues/20 I believe. Most of the changes are moving the files to the new dir structure. I tested the changes against my own kube cluster, but would be good to have someone else try it if possible as this is the first time I have done anything with the rbac stuff in kubernetes.

2017-05-18 20:58 UTC, bparees commented
Can you remove the test-scripts/resources dir/files?

2017-05-18 21:01 UTC, bparees commented on install/rc.yaml
> +        image: maleck13/service-broker-mongo:1.4
looks like you caught a personal change here.

i'm fine w/ the change to IfNotPresent on the pull policy though (but i believe that's the default, so you can just remove it entirely)

2017-05-18 21:02 UTC, maleck13 commented on install/rc.yaml
> +        image: maleck13/service-broker-mongo:1.4
yep 👍 That was me testing it :)

2017-05-18 21:15 UTC, bparees commented on install/rc.yaml
> -        imagePullPolicy: Never
i'm afraid this appears to be defaulting to a pull policy of "always" now.  sorry.  I could swear k8s only did that if the tag was explicitly ":latest".  Anyway please set it to IfNotPresent

2017-05-19 02:04 UTC, enj commented
This is the wrong approach.  It is nearly impossible to manually convert to RBAC and guarantee that everything is in sync.  Write a small helper program to handle the conversion as that will save you time and work in the future.

2017-05-19 07:41 UTC, maleck13 commented
@enj Thanks for response. Do you have an example in a code base that I could use for inspiration or is this something that would need to be done from scratch. 
@bparees Does this PR provide enough value and we can create a separate issue for the tool, or would you prefer we keep this one open?

2017-05-19 08:39 UTC, maleck13 commented
@enj sorry missed your link to the code in the related issue. I will take a look at what you linked to

2017-05-23 10:00 UTC, maleck13 commented
@bparees @enj Hey guys starting to put a tool together.  Little unsure about decoding the objects. I have used the ```UniversalDecoder``` and ``` UnstructuredJSONScheme``` is there a way to decode objects like the ClusterRole into their correct types currently only getting *runtime.Unstructured.
gist of my **very** rough code to show how I am decoding https://gist.github.com/maleck13/fac92043989a8a425c247e5e6f4f0432#file-convert-go-L75

2017-05-23 11:48 UTC, enj commented
You are missing the [imports](https://github.com/openshift/origin/blob/master/tools/etcdhelper/etcdhelper.go#L19-L22) that register objects.  That file has logic for decoding objects as well.

2017-05-23 11:49 UTC, maleck13 commented
@enj excellent thanks

2017-05-23 12:41 UTC, enj commented
As a side note, I feel like the correct approach would be to define (in Go, not YAML) the RBAC roles you need.  Then convert them to Openshift roles (in Go code).  Then dump both of list as YAML.  So the input to the tool is Go code, not YAML.

2017-05-28 08:31 UTC, pmorie commented
In general I think we should install the broker with a technology conventional for the environment it's being installed into.  For k8s, many people are going to want a helm chart to install their broker.  On OpenShift, people are going to expect templates.  I think there's probably enough divergence in the roles to maintain both an OpenShift template and a k8s template.

I am not saying no to this PR, but stating my own opinion about what this dimension of the experience should be like for users.

2017-05-29 07:38 UTC, maleck13 commented
@pmorie @enj @bparees How about we take this PR as an incremental improvement? Which it is as the roles and installation didn't work on k8s at all and now it does. We could then add new issues for helm installation and the roles generation tool?

2017-05-30 03:05 UTC, bparees commented
> @pmorie @enj @bparees How about we take this PR as an incremental improvement? Which it is as the roles and installation didn't work on k8s at all and now it does. We could then add new issues for helm installation and the roles generation tool?

i'm perfectly happy with that approach.

2017-05-30 03:45 UTC, enj commented
SGTM

2017-05-31 01:50 UTC, bparees requested changes
remove the unnecessary clusterrole and i'll merge.

2017-05-31 01:50 UTC, bparees commented on install/openshift/roles.yaml
> +  kind: ClusterRole
this cluster role is a default part of openshift now so we don't need it anymore.

2017-05-31 10:52 UTC, maleck13 commented
@bparees made that change

2017-05-31 20:54 UTC, bparees commented
awesome, thanks @maleck13!

2017-05-31 20:54 UTC, merged